import type {
  SmartAccountSignerSets,
  MatrixRow,
  OperationDraft,
  SecurityScenario,
  SessionKey,
  SignerSlot,
  SmartAccountState,
} from './types';

export const demoNotice =
  'Демонстрационный режим. Транзакции и подписи не отправляются в blockchain.';

export const smartAccount: SmartAccountState = {
  address: '0x71C4...9A12',
  network: 'Ethereum',
  status: 'Активен',
  signerEpoch: 7,
  recoveryDelayHours: 48,
  paymasterActive: true,
  spendingLimit: {
    token: 'USDT',
    dailyLimit: 5000,
    spentToday: 1250,
    singleOperationLimit: 500,
  },
  trustedRecipients: ['0xDSFRouter...0420', '0xTrusted...2048'],
};

export const demoSignerSets: SmartAccountSignerSets = {
  deviceSigners: [
    {
      type: 'DEVICE',
      signerId: '0xDeviceSigner0A1b2C3d4E5f6',
      displayIndex: 0,
      label: 'Основной Android',
      status: 'ACTIVE',
      addedAt: '2026-04-02',
      algorithm: 'P256',
      publicKeyX: '0x8fe1...42b7',
      publicKeyY: '0x17ac...09d1',
      deviceName: 'Pixel 9 Pro',
      hardwareBacked: true,
    },
    {
      type: 'DEVICE',
      signerId: '0xDeviceSigner1B2c3D4e5F6a7',
      displayIndex: 1,
      label: 'Резервный планшет',
      status: 'ACTIVE',
      addedAt: '2026-04-03',
      algorithm: 'P256',
      publicKeyX: '0x54aa...19c0',
      publicKeyY: '0x7b33...e5a4',
      deviceName: 'Galaxy Tab Secure',
      hardwareBacked: true,
    },
  ],
  socialSigners: [
    {
      type: 'SOCIAL',
      signerId: '0xSocialSigner0C3d4E5f6A7b8',
      displayIndex: 0,
      label: 'Google',
      status: 'ACTIVE',
      addedAt: '2026-04-02',
      provider: 'GOOGLE',
      socialPublicIdentifier: 'google:dsf-user@example.com',
      sessionStatus: 'ACTIVE',
    },
    {
      type: 'SOCIAL',
      signerId: '0xSocialSigner1D4e5F6a7B8c9',
      displayIndex: 1,
      label: 'Apple',
      status: 'ACTIVE',
      addedAt: '2026-04-02',
      provider: 'APPLE',
      socialPublicIdentifier: 'apple:dsf-user@privaterelay.appleid.com',
      sessionStatus: 'ACTIVE',
    },
    {
      type: 'SOCIAL',
      signerId: '0xSocialSigner2E5f6A7b8C9d0',
      displayIndex: 2,
      label: 'Passkey',
      status: 'ACTIVE',
      addedAt: '2026-04-04',
      provider: 'PASSKEY',
      socialPublicIdentifier: 'passkey:dsf-user',
      sessionStatus: 'ACTIVE',
    },
  ],
  arbiterSigners: [
    {
      type: 'ARBITER',
      signerId: '0xArbiterSigner0F6a7B8c9D0e1',
      displayIndex: 0,
      label: 'DSF HSM A',
      status: 'ACTIVE',
      addedAt: '2026-04-05',
      address: '0xArbiterA...1001',
      nodeLabel: 'DSF Arbiter A',
    },
    {
      type: 'ARBITER',
      signerId: '0xArbiterSigner1A7b8C9d0E1f2',
      displayIndex: 1,
      label: 'DSF HSM B',
      status: 'ACTIVE',
      addedAt: '2026-04-05',
      address: '0xArbiterB...1002',
      nodeLabel: 'DSF Arbiter B',
    },
    {
      type: 'ARBITER',
      signerId: '0xArbiterSigner2B8c9D0e1F2a3',
      displayIndex: 2,
      label: 'DSF HSM C',
      status: 'ACTIVE',
      addedAt: '2026-04-05',
      address: '0xArbiterC...1003',
      nodeLabel: 'DSF Arbiter C',
    },
  ],
};

export function createRegistrationSignerSets(step: number): SmartAccountSignerSets {
  return {
    deviceSigners: demoSignerSets.deviceSigners.map((signer) => ({
      ...signer,
      status: step >= 4 ? signer.status : 'NOT_REGISTERED',
    })),
    socialSigners: demoSignerSets.socialSigners.map((signer, index) => ({
      ...signer,
      status: step >= 3 || (step >= 2 && index === 0) ? signer.status : 'NOT_REGISTERED',
      sessionStatus: step >= 3 || (step >= 2 && index === 0) ? signer.sessionStatus : 'UNAVAILABLE',
    })),
    arbiterSigners: demoSignerSets.arbiterSigners.map((signer) => ({
      ...signer,
      status: step >= 7 ? signer.status : 'NOT_REGISTERED',
    })),
  };
}

export const defaultOperationDraft: OperationDraft = {
  type: 'TRANSFER',
  token: 'USDT',
  amount: 10000,
  targetContract: '0xTokenUSDT...dAC1',
  recipient: '0xNewRecipient...1000',
  recipientTrusted: false,
  validUntil: '2026-06-21T12:00:00Z',
  gasMode: 'USDT',
  sessionKeyMode: false,
  network: 'Ethereum',
  allowTransferBySessionKey: false,
};

export const signerSlots: SignerSlot[] = [
  {
    id: 'social',
    type: 'SOCIAL',
    title: 'Social Signer',
    keyType: 'OIDC / MPC / ECDSA',
    status: 'ACTIVE',
    addedAt: '2026-03-11',
    permissions: [
      'Подтверждать операции среднего риска',
      'Участвовать в recovery',
      'Подтверждать новое устройство',
    ],
    restrictions: ['Не может единолично менять критические настройки'],
    description:
      'Подписант, создаваемый или восстанавливаемый через социальную авторизацию, например Google, Apple, Privy или Web3Auth. Используется как удобный фактор входа и один из факторов восстановления.',
  },
  {
    id: 'device',
    type: 'DEVICE',
    title: 'Device Signer',
    keyType: 'P-256',
    status: 'ACTIVE',
    addedAt: '2026-04-02',
    publicKey: {
      x: '0x8fe1...42b7',
      y: '0x17ac...09d1',
    },
    storage: 'Android Keystore',
    permissions: [
      'Ежедневные операции',
      'Небольшие переводы',
      'Deposit',
      'Withdraw в пределах лимита',
      'Создание ограниченных session keys',
    ],
    restrictions: ['Не может один выполнять upgrade', 'Не может один удалить Arbiter'],
    description:
      'Ключ P-256, созданный в защищённом хранилище устройства. Приватный ключ не экспортируется, а подпись может подтверждаться биометрией.',
  },
  {
    id: 'arbiter',
    type: 'ARBITER',
    title: 'Arbiter Signer',
    keyType: 'ECDSA',
    status: 'ACTIVE',
    addedAt: '2026-04-05',
    permissions: [
      'Вторая подпись для больших сумм',
      'Подтверждение recovery',
      'Emergency freeze',
      'Risk approval',
    ],
    restrictions: ['Не может единолично перевести средства', 'Не может удалить других подписантов'],
    description:
      'Независимый серверный подписант, подтверждающий критические операции и восстановление. Не может единолично вывести активы.',
  },
  {
    id: 'recovery',
    type: 'RECOVERY',
    title: 'Recovery Signer',
    keyType: 'ECDSA / аппаратный фактор',
    status: 'ACTIVE',
    addedAt: '2026-04-07',
    permissions: [
      'Отменить подозрительный recovery',
      'Подтвердить восстановление',
      'Заморозить аккаунт',
      'Заменить потерянное устройство совместно с другим фактором',
    ],
    restrictions: ['Используется только при восстановлении или чрезвычайной ситуации'],
    description:
      'Резервный фактор, который хранится отдельно и используется только при восстановлении или чрезвычайной ситуации.',
  },
];

export const authorizationRows: MatrixRow[] = [
  {
    operation: 'Просмотр баланса',
    risk: 'NONE',
    device: '—',
    social: '—',
    arbiter: '—',
    recovery: '—',
    delay: '—',
    explanation: 'Просмотр не меняет состояние аккаунта и не требует подписи.',
  },
  {
    operation: 'Deposit в DSF',
    risk: 'LOW',
    device: 'Обязательно',
    social: '—',
    arbiter: '—',
    recovery: '—',
    delay: '—',
    explanation: 'Deposit увеличивает позицию в DSF и ограничен policy engine, поэтому достаточно Device Signer.',
  },
  {
    operation: 'Перевод до 500 USDT',
    risk: 'LOW',
    device: 'Обязательно',
    social: '—',
    arbiter: '—',
    recovery: '—',
    delay: '—',
    explanation: 'Сумма находится в пределах лимита одной операции и дневного лимита.',
  },
  {
    operation: 'Перевод на новый адрес',
    risk: 'MEDIUM',
    device: 'Обязательно',
    social: 'Обязательно',
    arbiter: '—',
    recovery: '—',
    delay: '—',
    explanation: 'Новый recipient не входит в allowlist, поэтому нужен независимый Social Signer.',
  },
  {
    operation: 'Перевод более 5 000 USDT',
    risk: 'HIGH',
    device: 'Обязательно',
    social: '—',
    arbiter: 'Обязательно',
    recovery: '—',
    delay: '—',
    explanation: 'Сумма превышает дневной лимит и требует Arbiter как второй фактор высокого риска.',
  },
  {
    operation: 'Создание Session Key',
    risk: 'MEDIUM',
    device: 'Обязательно',
    social: 'Обязательно',
    arbiter: '—',
    recovery: '—',
    delay: '—',
    explanation: 'Session Key получает будущие полномочия, поэтому требуется проверка двумя пользовательскими факторами.',
  },
  {
    operation: 'Добавление Signer',
    risk: 'HIGH',
    device: 'Обязательно',
    social: '—',
    arbiter: 'Обязательно',
    recovery: '—',
    delay: '24 часа',
    explanation: 'Новый signer меняет модель владения, поэтому требуется Arbiter и задержка на отмену.',
  },
  {
    operation: 'Удаление Arbiter',
    risk: 'CRITICAL',
    device: 'Обязательно',
    social: 'Обязательно',
    arbiter: '—',
    recovery: 'Recovery',
    delay: '72 часа',
    explanation: 'Удаление Arbiter ослабляет защиту, поэтому нужен Recovery Signer и длинный timelock.',
  },
  {
    operation: 'Recovery устройства',
    risk: 'CRITICAL',
    device: '—',
    social: 'Обязательно',
    arbiter: 'Обязательно',
    recovery: 'Опционально',
    delay: '48 часов',
    explanation: 'Если потеряны все Device, recovery строится на пороге 2 Social + 1 Arbiter или на отдельном резервном recovery-факторе.',
  },
  {
    operation: 'Upgrade аккаунта',
    risk: 'CRITICAL',
    device: 'Обязательно',
    social: 'Обязательно',
    arbiter: 'Обязательно',
    recovery: '—',
    delay: '7 дней',
    explanation: 'Upgrade меняет исполняемую логику аккаунта, поэтому требуется максимальный набор факторов и задержка.',
  },
];

export const sessionKeys: SessionKey[] = [
  {
    id: 'sk-1',
    name: 'Session Key #1',
    status: 'ACTIVE',
    validUntil: '24 часа',
    allowedContracts: ['DSF Router'],
    allowedMethods: ['deposit', 'withdraw', 'claim'],
    allowedTokens: ['USDT'],
    singleOperationLimit: 500,
    dailyLimit: 1000,
    transferAllowed: false,
    signerManagementAllowed: false,
    upgradeAllowed: false,
    recoveryAllowed: false,
  },
  {
    id: 'sk-2',
    name: 'DSF Claim автоматизация',
    status: 'ACTIVE',
    validUntil: '7 дней',
    allowedContracts: ['DSF Rewards'],
    allowedMethods: ['claim'],
    allowedTokens: ['DSF'],
    singleOperationLimit: 0,
    dailyLimit: 0,
    transferAllowed: false,
    signerManagementAllowed: false,
    upgradeAllowed: false,
    recoveryAllowed: false,
  },
];

export const securityScenarios: SecurityScenario[] = [
  {
    id: 'arbiter-compromised',
    title: 'Что произойдёт, если скомпрометирован Arbiter?',
    threat: 'Arbiter пытается подтвердить критическую операцию без пользователя.',
    mechanisms: ['multisigner validation', 'context-based policy', 'timelock', 'recovery'],
    outcome: [
      'Arbiter не может единолично вывести средства.',
      'Arbiter не может единолично заменить записи DeviceSigners[].',
      'Критические операции требуют другие независимые факторы.',
      'Arbiter можно заменить через усиленную процедуру.',
      'Смена Arbiter проходит через timelock.',
    ],
  },
];
